### ISSUE TITLE
Monospaced font for code.

### ISSUE THREAD

**Issue by croath** [NSHipster/articles#285]
I think it's better to read if the code has a monospaced font... For the reason that most of us are using monospaced fonts in IDE or editor everyday.

**Comment by rickytan** [comment]
I'm using Monaco

**Comment by natecook1000** [comment]
I've been meaning to ask about that! I just looked into it and the CSS is specifying `font-family: monospace`, which is actually monospace in English but [uses "Heiti TC"](https://trac.webkit.org/browser/trunk/Source/WebCore/Resources/DefaultFonts.plist.in?rev=114895) when the "zh-Hans" language attribute is given. I thought that was an intentional decision for NSHipster, but it's actually the browser making that change.

**Comment by natecook1000** [comment]
Fixed by NSHipster/nshipster.com@b13797197869addd5caf119280adf03ce58803e7. Thanks!

**Comment by croath** [comment]
Cool it all looks well now! Thanks @natecook1000 ! :lollipop:
