### ISSUE TITLE
Fix sample in Comparison Protocols article

### ISSUE THREAD

**Issue by natecook1000** [NSHipster/articles#373]
@huguesbr pointed out an error here: https://github.com/NSHipster/articles/commit/e4b977b30adc276ace718fa686e460a1a71d8d77

**Comment by huguesbr** [comment]
PR available here: https://github.com/NSHipster/articles/pull/375

**Comment by JSchaenzle** [comment]
In Objective-C we could us Mantle (https://github.com/Mantle/Mantle) to create model objects that were equatable. I found this really nice because we didn't have to go update an equality function if we add a member to an object. Is there anything similar for swift? If not, is there any good way of protecting against the case where you update an object but forget to update the equality operator?

**Comment by natecook1000** [comment]
@JSchaenzle Not possible in Swift, though I think they're discussing automatic Equatable conformance on the evolution list.

**Comment by natecook1000** [comment]
Fixed by @huguesbr — big thanks! :+1:

**Comment by huguesbr** [comment]
:bow:
