### ISSUE TITLE
NSIncrementalStore

### ISSUE THREAD

**Issue by rob-nash** [NSHipster/articles#501]
The last chapter of [this article](http://nshipster.com/nsincrementalstore/) mentions [AFIncrementalStore](https://github.com/AFNetworking/AFIncrementalStore), which has been discontinued.

After a quick look around [this code](https://github.com/andyshep/Palettes) looks like a good replacement to discuss maybe?

**Comment by mattt** [comment]
Thanks for pointing this out, @rob-nash. Sorry for taking so long to respond.

In retrospect, I don't think the article's promise of `NSIncrementalStore` has been borne out since its original publication in 2012. Rather than attempting to reframe the discussion, I've decided to retire the article, so that it no longer appears in the site index — at least for the time being.

Thanks for pointing out @andyshep's great work on this, though. I'd be really interested to hear if  improvements to CoreData and Foundation networking in general (and NSIncrementalStore specifically) make this approach truly viable for app development today.
