### ISSUE TITLE
WKWebView: 3d Touch

### ISSUE THREAD

**Issue by zapjonny** [NSHipster/articles#509]
3D Touch can be turned off for WKWebView using `.allowsLinkPreview` property. Felt that was kind of missing. Not sure about UIWebView.

**Comment by mattt** [comment]
Thanks for pointing this out, @zapjonny. The focus of this article is primarily about the top-level features and how they compare to `UIWebView`, rather than enumerating all of the available APIs. While this is a useful property to be aware of, it's not one that I think lends itself to this framing of the discussion.
