### ISSUE TITLE
HTML for figure is malformed on NSURLProtocol article

### ISSUE THREAD

**Issue by nonsensery** [NSHipster/articles#566]
### Description

The HTML markup of the [NSURLProtocol article](https://nshipster.com/nsurlprotocol/) is incorrect, resulting in most of the article contents appearing center-aligned.

### Discussion

The article's markdown source appears to be correct. It looks like there's a bug in the markdown => HTML conversion.

It looks like the converter is mistakenly escaping the closing `</figcaption>` and `</figure>` tags instead of passing them through.

The generated HTML looks like this:

```html
<figure id="url-loading-system">
  <figcaption>
    <p>The URL Loading System&lt;/figcaption&gt;</p>
    <table>
    …
    </table>
    <p>&lt;/figure&gt;</p>
    …
<p>So go forth and hack! I can’t wait to see what y’all come up with!</p>
</figcaption>
</figure>
```

**Comment by mattt** [comment]
Thanks so much for pointing this out and offering such a thorough diagnosis. Indeed, Kramdown is consistently unpredictable when it comes to embedded HTML, and is an ongoing source of issues for older articles like this one.

Looking at the article as a whole, I think the best solution was to remove the figure outright, since it wasn't really adding much to the discussion (627a3f0183e0dad2ada4f582d5233df8f97a2bd4). I also went through and made a few fixes in advance of a full update at some point later on.

Thanks again, @nonsensery!
