### ISSUE TITLE
Swift Collection Protocols: ContiguousArray clarification

### ISSUE THREAD

**Issue by jacobjennings** [NSHipster/articles#572]
I would love to hear more about ContiguousArray in the Swift Collection Protocols article, for instance, when would it be advantageous to use it over a standard array?

**Comment by mattt** [comment]
Hi @jacobjennings. The Swift Collection Protocols article is quite out of date, as much of the standard library has changed since Swift 1.2. As such, I've decided to retire the article so that it doesn't show up on the main index.

As a general rule, start with `Array` and consider alternatives only after determining that use of `Array` is a bottleneck for your particular use case. For the overwhelming majority of app developers (>99.999%), `Array` will be sufficient.

For additional guidance, see the official documentation for `ContiguousArray`: https://developer.apple.com/documentation/swift/contiguousarray
