### ISSUE TITLE
Xcode Plugins

### ISSUE THREAD

**Issue by devMoxie** [NSHipster/articles#607]
Seems like most of these plugins are either obsolete or unmaintained. I would love to here about what's being used these days. Thanks for all the info your site provides! And thanks for showing the publication date for the articles. It's been driving me insane lately trying to figure out if a post is out of date or now.

**Comment by mattt** [comment]
Indeed, Xcode Plugins have been unsupported since 2016. I've updated this article (e8b0ea7) to note this deprecation, directing readers to our [recent article](https://nshipster.com/xcode-source-extensions/) about their follow-up, Xcode Source Extensions. Thanks for the reminder!

And I'm 100% with you regarding frustration with undated posts. Worse still are websites that regularly reset publication timestamps for posts, irrespective of any changes — a trend I've noticed recently and hope doesn't catch on.
