### ISSUE TITLE
PHImageManager - PHImageRequestOptionsDeliveryMode

### ISSUE THREAD

**Issue by andrewbuilder** [NSHipster/articles#633]
Hi Mattt,
In your article under the heading PHImageRequestOptionsDeliveryMode, you state under `.Opportunistic`...

> This option is not available if the synchronous property is false.

I'm new to PhotoKit so may be incorrect in my assessment here, but should this not be the opposite. 
Also under `.HighQualityFormat` you state this is the only option with the (now) `.isSynchronous` property is true - leads me to believe that the statement under `.Opportunistic` is a mistake.

Quick moment to comment on NSHipster... one of the best blogs for Swift and Obj-C. Huge thanks to you and your team - I've learned so much from your blog over the years.
Andrew

**Comment by mattt** [comment]
Hi @andrewbuilder. Thanks for the kind words!

To be honest, I haven't touched PhotoKit myself since the article first went out ~5 years ago. What you're saying makes sense, and I suspect your assumptions are correct. That statement specifically was a direct quote from Apple's documentation at the time of writing, which [have since been updated](https://developer.apple.com/documentation/photokit/phimagerequestoptionsdeliverymode/opportunistic) and no longer make that claim.

Taking another look at this now, I think the article has the effect of over-promising on the framework's capabilities without offering any unique insight. Not our best work, to say the least. As such, I've gone ahead and retired it for the time being (it'll remain accessible, but no longer be listed or indexed on the site).
