### ISSUE TITLE
Behavior of -[NSData description] changes only when app is built with iOS 13 SDK

### ISSUE THREAD

**Issue by kambala-decapitator** [NSHipster/articles#665]
I think it's important to note in https://nshipster.com/apns-device-tokens/, as most of the existing apps aren't affected because they're built with iOS 12 SDK.

**Comment by mattt** [comment]
I agree, which is why I made a point to call that out at the end of [this section](https://nshipster.com/apns-device-tokens/#relitigating-the-past-with-swift-3):

https://github.com/NSHipster/articles/commit/889e0f5ae3ffb994beeb26916459368b29853600#diff-09689c1063006765e980821e8fc4da20R262-R273

Do you have any suggestions for how this could be made clearer?

**Comment by kambala-decapitator** [comment]
Not sure if "compiled with the iOS 13 SDK" was present when I was reading the article, but my eye only caught "This is true whether your app is written in Swift or Objective-C." because it's in bold. I think that simply making the 13 SDK part bold too would make it more noticeable.

**Comment by mattt** [comment]
Thanks for your feedback, @kambala-decapitator. Rather than try to attract more attention to the part about the iOS 13 SDK, I removed the emphasis about Swift and Objective-C with ff1c6ad.
