### ISSUE TITLE
Diffable Articles

### ISSUE THREAD

**Issue by therealbnut** [NSHipster/articles#704]
I came to this repo after hearing an article had updating from your twitter. I was hoping to see a diff. Because new files seems to be made for each change (with a date in the name) the diff doesn’t really work so easily.

It’d be great to remove the date and use git’s date/versioning instead :)

**Comment by mattt** [comment]
Although GitHub's UI [doesn't currently show this](https://github.com/isaacs/github/issues/900), you can see changes across file renames with the following command:

```terminal
$ git log --stat -p --follow -- 2020-02-27-xcconfig.md
```

Alternatively, you can compare versions on [Wayback Machine](http://web.archive.org/web/20200215000000*/https://nshipster.com/xcconfig/)

> It’d be great to remove the date and use git’s date/versioning instead :)

NSHipster.com is built with Jekyll, which requires posts to have filenames in the format `YEAR-MONTH-DAY-title.MARKUP`, so that's not an option.

**Comment by therealbnut** [comment]
Thanks for clarifying
